const GAMES = [
  {
    id: "g1",
    name: "God of War",
    desc: "Kratos y Atreus exploran la mitología nórdica.",
    price: 39990,
    category: "accion",
    cover: "https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg"
  },
  {
    id: "g2",
    name: "Doom Eternal",
    desc: "Acción frenética contra demonios en la Tierra.",
    price: 29990,
    category: "accion",
    cover: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2020/01/doom-eternal-portada-ficha-02-1856821.jpg?tf=1200x"
  },
  {
    id: "g3",
    name: "Uncharted 4",
    desc: "Aventura y tesoros con Nathan Drake.",
    price: 34990,
    category: "aventura",
    cover: "https://static.wikia.nocookie.net/unchartedpedia/images/8/8f/Uncharted_4_portada.jpeg/revision/latest?cb=20211230130123&path-prefix=es"
  },
  {
    id: "g4",
    name: "Celeste",
    desc: "Plataformas indie sobre superación personal.",
    price: 9990,
    category: "indie",
    cover: "https://media.vandal.net/m/44239/celeste-2018128121116_11.jpg"
  },
  {
    id: "g5",
    name: "Hollow Knight",
    desc: "Metroidvania indie con exploración y combates.",
    price: 11990,
    category: "indie",
    cover: "https://i.3djuegos.com/juegos/11596/hollow_knight/fotos/ficha/hollow_knight-3915488.jpg"
  }
  ,{id : "g6", name: "The Last of Us Part II",
     desc: "Secuela aclamada por la crítica de The Last of Us.", 
     price: 49990, 
     category: "aventura", 
     cover: "https://static.wikia.nocookie.net/thelastofus/images/f/f7/TLOUPartIICoverArt.png/revision/latest/scale-to-width-down/284?cb=20211113162759&path-prefix=es" },
  {id : "g7", name: "Red Dead Redemption 2",
      desc: "Aventura épica en el Viejo Oeste.", 
      price: 59990,
      category: "aventura", 
      cover: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg" },
  {id : "g8", name: "Stardew Valley",
      desc: "Simulador de granja y vida en un pueblo.", 
      price: 14990, 
      category: "indie", 
      cover: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2017/02/stardew-valley.jpg?tf=1200x" },
  {id : "g9", name: "Cyberpunk 2077",
      desc: "RPG futurista en un mundo abierto.", 
      price: 39990, 
      category: "accion", 
      cover: "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg" },
  {id : "g10", name: "The Witcher 3: Wild Hunt",
      desc: "RPG de fantasía con una historia profunda.", 
      price: 49990, 
      category: "aventura", 
      cover: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg" },
      {id : "g11", name: "Minecraft",
      desc: "Juego de construcción y supervivencia en un mundo abierto.", 
      price: 26990, 
      category: "indie", 
      cover: "https://i.pinimg.com/474x/d2/45/9d/d2459de3246eb8a7d3504903d200f26c.jpg" },
      {id : "g12",
        name: "fifa 23",
        desc: "Simulador de fútbol con gráficos realistas.",
        price: 59990,
        category: "deportes",
        cover: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2022/07/fifa-23-2763291.jpg?tf=3840x"
      },
      {id : "g13",
        name: "NBA 2K23",
        desc: "Juego de baloncesto con modos de juego variados.",
        price: 49990,
        category: "deportes",
        cover: "https://i.3djuegos.com/juegos/18640/nba_2k23/fotos/ficha/nba_2k23-5739349.webp"
      },
      {id : "g14",
        name: "Forza Horizon 5",
        desc: "Juego de carreras en un mundo abierto basado en México.",
        price: 69990,
        category: "carreras",
        cover: "https://image.api.playstation.com/vulcan/ap/rnd/202502/0323/d808653f2c2453e79433628e31f673ef3976c6771d39228a.png"
      },
      {id : "g15",
        name: "Gran Turismo 7",
        desc: "Simulador de carreras con una amplia selección de coches.",
        price: 59990,
        category: "carreras",
        cover: "https://image.api.playstation.com/vulcan/ap/rnd/202109/1321/3mjMyRiJaq8lw1EFWiTCUJRV.png"
      },
      {id : "g16",
        name: "F1 2021",
        desc: "Simulador de Fórmula 1 con todos los equipos y pilotos oficiales.",
        price: 49990,
        category: "carreras",
        cover: "https://upload.wikimedia.org/wikipedia/en/8/86/F1_2021_cover_art.jpg"
      },
      {id : "g17",
        name: "nhl 23",
        desc: "Simulador de hockey sobre hielo con gráficos realistas.",
        price: 49990,
        category: "deportes",
        cover: "https://media.d3.nhle.com/image/private/t_ratio1_1-size20/prd/sy2w5qlgaplsx5ldmksi"
      },
      {id : "g18",
        name: "Madden NFL 23",
        desc: "Simulador de fútbol americano con modos de juego variados.",
        price: 49990,
        category: "deportes",
        cover: "https://media.contentapi.ea.com/content/dam/ea/madden-nfl/madden-nfl-23/news/common/copy-of-eas-madden23-gen5-ame-keyart-vert-cmyk.jpg.adapt.320w.jpg"
      },
      {id : "g19",
        name: "mortal kombat 11",
        desc: "Juego de lucha con personajes icónicos y gráficos impresionantes.",
        price: 39990,
        category: "accion",
        cover: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2019/03/Mortal%20Kombat%2011%20caratula.jpg?tf=3840x"
      },
      {id : "g20",
        name: "Street Fighter V",
        desc: "Juego de lucha con una amplia variedad de personajes y estilos de juego.",
        price: 29990,
        category: "accion",
        cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsvUymqkxXzl4SCcWkRsA-agBU1efnO7tDXA&s"
      }
];